# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class MetricName(str, Enum):
    """
    MetricName
    """

    """
    allowed enum values
    """
    UNKNOWN = 'UNKNOWN'
    CPU_TOTAL_PERCENT = 'CPU_TOTAL_PERCENT'
    MEM_RSS = 'MEM_RSS'
    HTTP_THROUGHPUT = 'HTTP_THROUGHPUT'
    HTTP_RESPONSE_TIME_50_P = 'HTTP_RESPONSE_TIME_50P'
    HTTP_RESPONSE_TIME_90_P = 'HTTP_RESPONSE_TIME_90P'
    HTTP_RESPONSE_TIME_99_P = 'HTTP_RESPONSE_TIME_99P'
    HTTP_RESPONSE_TIME_MAX = 'HTTP_RESPONSE_TIME_MAX'
    PUBLIC_DATA_TRANSFER_IN = 'PUBLIC_DATA_TRANSFER_IN'
    PUBLIC_DATA_TRANSFER_OUT = 'PUBLIC_DATA_TRANSFER_OUT'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of MetricName from a JSON string"""
        return cls(json.loads(json_str))


