# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class OrganizationDetailedStatus(str, Enum):
    """
    OrganizationDetailedStatus
    """

    """
    allowed enum values
    """
    NEW = 'NEW'
    EMAIL_NOT_VALIDATED = 'EMAIL_NOT_VALIDATED'
    BILLING_INFO_MISSING = 'BILLING_INFO_MISSING'
    LOCKED = 'LOCKED'
    PAYMENT_FAILURE = 'PAYMENT_FAILURE'
    VALID = 'VALID'
    PENDING_VERIFICATION = 'PENDING_VERIFICATION'
    VERIFICATION_FAILED = 'VERIFICATION_FAILED'
    REVIEWING_ACCOUNT = 'REVIEWING_ACCOUNT'
    PLAN_UPGRADE_REQUIRED = 'PLAN_UPGRADE_REQUIRED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of OrganizationDetailedStatus from a JSON string"""
        return cls(json.loads(json_str))


