# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


from __future__ import annotations
import json
from enum import Enum
from typing_extensions import Self


class PersistentVolumeStatus(str, Enum):
    """
    PersistentVolumeStatus
    """

    """
    allowed enum values
    """
    PERSISTENT_VOLUME_STATUS_INVALID = 'PERSISTENT_VOLUME_STATUS_INVALID'
    PERSISTENT_VOLUME_STATUS_ATTACHED = 'PERSISTENT_VOLUME_STATUS_ATTACHED'
    PERSISTENT_VOLUME_STATUS_DETACHED = 'PERSISTENT_VOLUME_STATUS_DETACHED'
    PERSISTENT_VOLUME_STATUS_DELETING = 'PERSISTENT_VOLUME_STATUS_DELETING'
    PERSISTENT_VOLUME_STATUS_DELETED = 'PERSISTENT_VOLUME_STATUS_DELETED'

    @classmethod
    def from_json(cls, json_str: str) -> Self:
        """Create an instance of PersistentVolumeStatus from a JSON string"""
        return cls(json.loads(json_str))


