# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.organization_quotas_api import OrganizationQuotasApi


class TestOrganizationQuotasApi(unittest.TestCase):
    """OrganizationQuotasApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationQuotasApi()

    def tearDown(self) -> None:
        pass

    def test_get_quotas(self) -> None:
        """Test case for get_quotas

        """
        pass


if __name__ == '__main__':
    unittest.main()
