# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.secret_type import SecretType

class TestSecretType(unittest.TestCase):
    """SecretType unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def testSecretType(self):
        """Test SecretType"""
        # inst = SecretType()

if __name__ == '__main__':
    unittest.main()
