# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.list_apps_reply import ListAppsReply

class TestListAppsReply(unittest.TestCase):
    """ListAppsReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ListAppsReply:
        """Test ListAppsReply
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ListAppsReply`
        """
        model = ListAppsReply()
        if include_optional:
            return ListAppsReply(
                apps = [
                    openapi_client.models.app_list_item.AppListItem(
                        id = '', 
                        name = '', 
                        organization_id = '', 
                        updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        domains = [
                            openapi_client.models.domain.Domain(
                                id = '', 
                                organization_id = '', 
                                name = '', 
                                created_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                updated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                status = 'PENDING', 
                                type = 'AUTOASSIGNED', 
                                app_id = '', 
                                deployment_group = '', 
                                verified_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                                intended_cname = '', 
                                messages = [
                                    ''
                                    ], 
                                version = '', )
                            ], 
                        status = 'STARTING', 
                        messages = [
                            ''
                            ], )
                    ],
                limit = 56,
                offset = 56,
                count = 56
            )
        else:
            return ListAppsReply(
        )
        """

    def testListAppsReply(self):
        """Test ListAppsReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
