# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.deployments_api import DeploymentsApi


class TestDeploymentsApi(unittest.TestCase):
    """DeploymentsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = DeploymentsApi()

    def tearDown(self) -> None:
        pass

    def test_cancel_deployment(self) -> None:
        """Test case for cancel_deployment

        Cancel Deployment
        """
        pass

    def test_get_deployment(self) -> None:
        """Test case for get_deployment

        Get Deployment
        """
        pass

    def test_list_deployment_events(self) -> None:
        """Test case for list_deployment_events

        List Deployment events
        """
        pass

    def test_list_deployments(self) -> None:
        """Test case for list_deployments

        List Deployments
        """
        pass


if __name__ == '__main__':
    unittest.main()
