# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.quotas import Quotas

class TestQuotas(unittest.TestCase):
    """Quotas unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> Quotas:
        """Test Quotas
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `Quotas`
        """
        model = Quotas()
        if include_optional:
            return Quotas(
                apps = '',
                services = '',
                domains = '',
                services_by_app = '',
                service_provisioning_concurrency = '',
                memory_mb = '',
                instance_types = [
                    ''
                    ],
                regions = [
                    ''
                    ],
                max_organization_members = '',
                max_instances_by_type = {
                    'key' : ''
                    }
            )
        else:
            return Quotas(
        )
        """

    def testQuotas(self):
        """Test Quotas"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
