# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.database_source import DatabaseSource

class TestDatabaseSource(unittest.TestCase):
    """DatabaseSource unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DatabaseSource:
        """Test DatabaseSource
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DatabaseSource`
        """
        model = DatabaseSource()
        if include_optional:
            return DatabaseSource(
                neon_postgres = openapi_client.models.neon_postgres_database.NeonPostgresDatabase(
                    pg_version = 56, 
                    region = '', 
                    instance_type = '', 
                    roles = [
                        openapi_client.models.neon_postgres_database/neon_role.NeonPostgresDatabase.NeonRole(
                            name = '', 
                            secret = '', )
                        ], 
                    databases = [
                        openapi_client.models.neon_postgres_database/neon_database.NeonPostgresDatabase.NeonDatabase(
                            name = '', 
                            owner = '', )
                        ], )
            )
        else:
            return DatabaseSource(
        )
        """

    def testDatabaseSource(self):
        """Test DatabaseSource"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
