# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.organization_invitations_api import OrganizationInvitationsApi


class TestOrganizationInvitationsApi(unittest.TestCase):
    """OrganizationInvitationsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationInvitationsApi()

    def tearDown(self) -> None:
        pass

    def test_create_organization_invitation(self) -> None:
        """Test case for create_organization_invitation

        """
        pass

    def test_delete_organization_invitation(self) -> None:
        """Test case for delete_organization_invitation

        """
        pass

    def test_get_organization_invitation(self) -> None:
        """Test case for get_organization_invitation

        """
        pass

    def test_list_organization_invitations(self) -> None:
        """Test case for list_organization_invitations

        """
        pass

    def test_resend_organization_invitation(self) -> None:
        """Test case for resend_organization_invitation

        """
        pass


if __name__ == '__main__':
    unittest.main()
