# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.organization_members_api import OrganizationMembersApi


class TestOrganizationMembersApi(unittest.TestCase):
    """OrganizationMembersApi unit test stubs"""

    def setUp(self) -> None:
        self.api = OrganizationMembersApi()

    def tearDown(self) -> None:
        pass

    def test_list_organization_members(self) -> None:
        """Test case for list_organization_members

        List organization members
        """
        pass

    def test_remove_organization_member(self) -> None:
        """Test case for remove_organization_member

        Remove an organization member
        """
        pass


if __name__ == '__main__':
    unittest.main()
