# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.persistent_volumes_api import PersistentVolumesApi


class TestPersistentVolumesApi(unittest.TestCase):
    """PersistentVolumesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = PersistentVolumesApi()

    def tearDown(self) -> None:
        pass

    def test_create_persistent_volume(self) -> None:
        """Test case for create_persistent_volume

        Create a PersistentVolume
        """
        pass

    def test_delete_persistent_volume(self) -> None:
        """Test case for delete_persistent_volume

        Delete a PersistentVolume
        """
        pass

    def test_get_persistent_volume(self) -> None:
        """Test case for get_persistent_volume

        Get a PersistentVolume
        """
        pass

    def test_list_persistent_volumes(self) -> None:
        """Test case for list_persistent_volumes

        List all PersistentVolumes
        """
        pass

    def test_update_persistent_volume(self) -> None:
        """Test case for update_persistent_volume

        Update a PersistentVolume
        """
        pass


if __name__ == '__main__':
    unittest.main()
