# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.region_list_item import RegionListItem

class TestRegionListItem(unittest.TestCase):
    """RegionListItem unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> RegionListItem:
        """Test RegionListItem
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `RegionListItem`
        """
        model = RegionListItem()
        if include_optional:
            return RegionListItem(
                id = '',
                name = '',
                coordinates = [
                    ''
                    ],
                status = '',
                instances = [
                    ''
                    ],
                datacenters = [
                    ''
                    ]
            )
        else:
            return RegionListItem(
        )
        """

    def testRegionListItem(self):
        """Test RegionListItem"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
