# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.delete_user_reply import DeleteUserReply

class TestDeleteUserReply(unittest.TestCase):
    """DeleteUserReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeleteUserReply:
        """Test DeleteUserReply
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeleteUserReply`
        """
        model = DeleteUserReply()
        if include_optional:
            return DeleteUserReply(
                user = {id=78352123-a06f-4ec2-81ed-27a056725385, email=john@snow.com, name=John Snow, avatar_url=https://www.gravatar.com/avatar/00000000000000000000000000000000, is_admin=false, is_test=true, two_factor_authentication=false, last_login=0001-01-01T00:00:00Z, last_login_id=10.1.1.1, updated_at=0001-01-01T00:00:00Z, created_at=0001-01-01T00:00:00Z, newsletter_subscribed=true, email_validated=true}
            )
        else:
            return DeleteUserReply(
        )
        """

    def testDeleteUserReply(self):
        """Test DeleteUserReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
