# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.apps_api import AppsApi


class TestAppsApi(unittest.TestCase):
    """AppsApi unit test stubs"""

    def setUp(self) -> None:
        self.api = AppsApi()

    def tearDown(self) -> None:
        pass

    def test_create_app(self) -> None:
        """Test case for create_app

        Create App
        """
        pass

    def test_delete_app(self) -> None:
        """Test case for delete_app

        Delete App
        """
        pass

    def test_get_app(self) -> None:
        """Test case for get_app

        Get App
        """
        pass

    def test_list_app_events(self) -> None:
        """Test case for list_app_events

        List App events
        """
        pass

    def test_list_apps(self) -> None:
        """Test case for list_apps

        List App
        """
        pass

    def test_pause_app(self) -> None:
        """Test case for pause_app

        Pause App
        """
        pass

    def test_resume_app(self) -> None:
        """Test case for resume_app

        Resume App
        """
        pass

    def test_update_app(self) -> None:
        """Test case for update_app

        Update App
        """
        pass

    def test_update_app2(self) -> None:
        """Test case for update_app2

        Update App
        """
        pass


if __name__ == '__main__':
    unittest.main()
