# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.deployment_provisioning_info_stage_build_attempt import DeploymentProvisioningInfoStageBuildAttempt

class TestDeploymentProvisioningInfoStageBuildAttempt(unittest.TestCase):
    """DeploymentProvisioningInfoStageBuildAttempt unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> DeploymentProvisioningInfoStageBuildAttempt:
        """Test DeploymentProvisioningInfoStageBuildAttempt
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `DeploymentProvisioningInfoStageBuildAttempt`
        """
        model = DeploymentProvisioningInfoStageBuildAttempt()
        if include_optional:
            return DeploymentProvisioningInfoStageBuildAttempt(
                id = 56,
                status = 'UNKNOWN',
                messages = [
                    ''
                    ],
                started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'),
                finished_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f')
            )
        else:
            return DeploymentProvisioningInfoStageBuildAttempt(
        )
        """

    def testDeploymentProvisioningInfoStageBuildAttempt(self):
        """Test DeploymentProvisioningInfoStageBuildAttempt"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
