# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.get_organization_usage_details_reply import GetOrganizationUsageDetailsReply

class TestGetOrganizationUsageDetailsReply(unittest.TestCase):
    """GetOrganizationUsageDetailsReply unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> GetOrganizationUsageDetailsReply:
        """Test GetOrganizationUsageDetailsReply
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `GetOrganizationUsageDetailsReply`
        """
        model = GetOrganizationUsageDetailsReply()
        if include_optional:
            return GetOrganizationUsageDetailsReply(
                usage_details = [
                    openapi_client.models.usage_details.UsageDetails(
                        organization_id = '', 
                        instance_id = '', 
                        app_id = '', 
                        app_name = '', 
                        service_id = '', 
                        service_name = '', 
                        regional_deployment_id = '', 
                        region = '', 
                        deployment_id = '', 
                        instance_type = '', 
                        duration_seconds = 56, 
                        started_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), 
                        terminated_at = datetime.datetime.strptime('2013-10-20 19:20:30.00', '%Y-%m-%d %H:%M:%S.%f'), )
                    ],
                limit = 56,
                offset = 56,
                count = 56,
                order = ''
            )
        else:
            return GetOrganizationUsageDetailsReply(
        )
        """

    def testGetOrganizationUsageDetailsReply(self):
        """Test GetOrganizationUsageDetailsReply"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
