# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.app_usage import AppUsage

class TestAppUsage(unittest.TestCase):
    """AppUsage unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> AppUsage:
        """Test AppUsage
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `AppUsage`
        """
        model = AppUsage()
        if include_optional:
            return AppUsage(
                app_id = '',
                app_name = '',
                services = [
                    openapi_client.models.service_usage.ServiceUsage(
                        service_id = '', 
                        service_name = '', 
                        regions = {
                            'key' : openapi_client.models.region_usage.RegionUsage(
                                instances = {
                                    'key' : openapi_client.models.instance_usage.InstanceUsage(
                                        duration_seconds = 56, )
                                    }, )
                            }, )
                    ]
            )
        else:
            return AppUsage(
        )
        """

    def testAppUsage(self):
        """Test AppUsage"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
