# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.api.services_api import ServicesApi


class TestServicesApi(unittest.TestCase):
    """ServicesApi unit test stubs"""

    def setUp(self) -> None:
        self.api = ServicesApi()

    def tearDown(self) -> None:
        pass

    def test_autocomplete(self) -> None:
        """Test case for autocomplete

        Generate autocomplete definition for a service
        """
        pass

    def test_create_service(self) -> None:
        """Test case for create_service

        Create Service
        """
        pass

    def test_delete_service(self) -> None:
        """Test case for delete_service

        Delete Service
        """
        pass

    def test_get_service(self) -> None:
        """Test case for get_service

        Get Service
        """
        pass

    def test_list_service_events(self) -> None:
        """Test case for list_service_events

        List Service events
        """
        pass

    def test_list_services(self) -> None:
        """Test case for list_services

        List Services
        """
        pass

    def test_pause_service(self) -> None:
        """Test case for pause_service

        Pause Service
        """
        pass

    def test_re_deploy(self) -> None:
        """Test case for re_deploy

        ReDeploy Service
        """
        pass

    def test_resume_service(self) -> None:
        """Test case for resume_service

        Resume Service
        """
        pass

    def test_update_service(self) -> None:
        """Test case for update_service

        Update Service
        """
        pass

    def test_update_service2(self) -> None:
        """Test case for update_service2

        Update Service
        """
        pass


if __name__ == '__main__':
    unittest.main()
