# coding: utf-8

"""
    Koyeb Rest API

    The Koyeb API allows you to interact with the Koyeb platform in a simple, programmatic way using conventional HTTP requests. 

    The version of the OpenAPI document: 1.0.0
    Generated by OpenAPI Generator (https://openapi-generator.tech)

    Do not edit the class manually.
"""  # noqa: E501


import unittest

from openapi_client.models.service_state import ServiceState

class TestServiceState(unittest.TestCase):
    """ServiceState unit test stubs"""

    def setUp(self):
        pass

    def tearDown(self):
        pass

    def make_instance(self, include_optional) -> ServiceState:
        """Test ServiceState
            include_option is a boolean, when False only required
            params are included, when True both required and
            optional params are included """
        # uncomment below to create an instance of `ServiceState`
        """
        model = ServiceState()
        if include_optional:
            return ServiceState(
                desired_deployment = openapi_client.models.desired_deployment.DesiredDeployment(
                    groups = [
                        openapi_client.models.desired_deployment/group.DesiredDeployment.Group(
                            name = '', 
                            deployment_ids = [
                                ''
                                ], )
                        ], ),
                auto_release = openapi_client.models.auto_release.AutoRelease(
                    groups = [
                        openapi_client.models.configuration_extracted_from_the_latest_deployment_in_this_deployment_group.Configuration extracted from the latest deployment in this deployment_group(
                            name = '', 
                            repository = '', 
                            git_ref = '', 
                            latest_sha = '', )
                        ], )
            )
        else:
            return ServiceState(
        )
        """

    def testServiceState(self):
        """Test ServiceState"""
        # inst_req_only = self.make_instance(include_optional=False)
        # inst_req_and_optional = self.make_instance(include_optional=True)

if __name__ == '__main__':
    unittest.main()
